import { Order, User, CatProfile, Review } from "@/types";

// Mock 用户数据
export const MOCK_USERS: User[] = [
  {
    id: "user-1",
    name: "小明",
    phone: "138****1234",
    role: "user",
    address: "南京市江宁区东山街道万达广场",
    savedAddresses: ["南京市江宁区东山街道万达广场2栋1403", "南京市江宁区义乌小商品城旁金轮新都汇8栋1201"],
    rating: 4.8,
    createdAt: "2026-01-15",
  },
  {
    id: "user-2",
    name: "阿花",
    phone: "136****9012",
    role: "user",
    address: "南京市江宁区百家湖花园",
    savedAddresses: ["南京市江宁区百家湖花园12栋502"],
    rating: 4.6,
    createdAt: "2026-01-20",
  },
  {
    id: "user-3",
    name: "猫奴小王",
    phone: "137****3456",
    role: "user",
    address: "南京市江宁区翠屏山小区",
    savedAddresses: ["南京市江宁区翠屏山小区7栋301"],
    rating: 4.9,
    createdAt: "2026-02-01",
  },
  {
    id: "feeder-1",
    name: "猫猫侠",
    phone: "139****5678",
    role: "feeder",
    avatar: "",
    rating: 4.9,
    totalOrders: 128,
    bio: "资深铲屎官，养猫5年，擅长应对各种性格的猫咪。持有宠物护理证书。",
    serviceArea: "江宁区",
    createdAt: "2026-01-10",
  },
];

// Mock 订单数据
export const MOCK_ORDERS: Order[] = [
  {
    id: "order-1",
    userId: "user-1",
    feederId: undefined,
    status: "pending",
    catCount: 2,
    startDate: "2026-03-01",
    endDate: "2026-03-03",
    notes: "两只英短，只喂干粮，每天一次",
    address: "南京市江宁区东山街道万达广场2栋1403",
    pricePerDay: 50,
    totalPrice: 300,
    createdAt: "2026-02-25",
  },
  {
    id: "order-2",
    userId: "user-2",
    feederId: undefined,
    status: "pending",
    catCount: 1,
    startDate: "2026-03-05",
    endDate: "2026-03-07",
    notes: "布偶猫，需要喂湿粮+铲屎，猫粮在厨房柜子里",
    address: "南京市江宁区百家湖花园12栋502",
    pricePerDay: 50,
    totalPrice: 150,
    createdAt: "2026-02-25",
  },
  {
    id: "order-3",
    userId: "user-3",
    feederId: undefined,
    status: "pending",
    catCount: 3,
    startDate: "2026-03-02",
    endDate: "2026-03-06",
    notes: "三只橘猫，饭量大，干粮湿粮各一顿，需要陪玩10分钟",
    address: "南京市江宁区翠屏山小区7栋301",
    pricePerDay: 50,
    totalPrice: 750,
    createdAt: "2026-02-24",
  },
  {
    id: "order-4",
    userId: "user-1",
    feederId: undefined,
    status: "pending",
    catCount: 1,
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    notes: "美短，比较胆小，进门动作轻一点",
    address: "南京市江宁区义乌小商品城旁金轮新都汇8栋1201",
    pricePerDay: 50,
    totalPrice: 150,
    createdAt: "2026-02-24",
  },
  {
    id: "order-5",
    userId: "user-2",
    feederId: undefined,
    status: "pending",
    catCount: 2,
    startDate: "2026-03-08",
    endDate: "2026-03-09",
    notes: "两只暹罗，每天喂两次，早晚各一次",
    address: "南京市江宁区九龙湖国际企业总部园6栋",
    pricePerDay: 50,
    totalPrice: 200,
    createdAt: "2026-02-23",
  },
];

// Mock 猫咪档案
export const MOCK_CATS: CatProfile[] = [
  {
    id: "cat-1",
    ownerId: "user-1",
    name: "大橘",
    breed: "英短",
    age: 3,
    personality: "温顺亲人，喜欢被摸下巴",
    dietNotes: "只吃干粮，每天一次，一次50g",
  },
  {
    id: "cat-2",
    ownerId: "user-1",
    name: "小白",
    breed: "英短",
    age: 2,
    personality: "胆小怕生，进门后会躲起来",
    dietNotes: "干粮为主，偶尔加罐头",
  },
  {
    id: "cat-3",
    ownerId: "user-2",
    name: "布丁",
    breed: "布偶",
    age: 1,
    personality: "粘人，喜欢跟着人走",
    dietNotes: "湿粮+干粮混喂，猫粮在厨房柜子里",
  },
  {
    id: "cat-4",
    ownerId: "user-3",
    name: "橘一",
    breed: "橘猫",
    age: 4,
    personality: "贪吃，饭量大",
    dietNotes: "干粮湿粮各一顿，控制食量",
  },
  {
    id: "cat-5",
    ownerId: "user-3",
    name: "橘二",
    breed: "橘猫",
    age: 3,
    personality: "活泼好动，喜欢逗猫棒",
    dietNotes: "同橘一",
  },
  {
    id: "cat-6",
    ownerId: "user-3",
    name: "橘三",
    breed: "橘猫",
    age: 2,
    personality: "安静，喜欢晒太阳",
    dietNotes: "同橘一",
  },
];
